### ISSUE TITLE
BUG_autocompletion_not_work_non_english

### ISSUE THREAD

**Issue by dbilee** [victorbalssa/abacus#67]
**Describe the bug**
The autocompletion on account type and categories not work if the content is not Engish.  
This works fine on FireflyIII web.

**To Reproduce**
1. Go to 'New Transaction'
2. Click on 'Source account'
3. Type some keyword to check autocompletion
4. It's ok f the input is engish, but not work if it's not English

**Expected behavior**
The autocompletion should work on any language.

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS 16.2
 - Version 0.4.0
 - FireflyIII: 5.7.18

**Comment by victorbalssa** [comment]
Thank you for the feedback @dbilee,
Can you tell us what language you use?
Victor

**Comment by dbilee** [comment]
Great thanks for your reply.  
Chinese, zh_cn.  

Another question is the autocomplete list only have 5 items,how can I config it?

**Comment by victorbalssa** [comment]
The autocomplete list is hard coded to 5 for the user experience i.e. to not take up too much screen when open.
The list will update as you use the search (fix in progress for `zh_cn`)

**Comment by dbilee** [comment]
Ok,thanks for your quick response.  
I’ve found the client has been auto updated,(hot fix?) and the source account has fixed, but other input blanks haven’t.

Buy the way, there’s a translation issue maybe I can fix it later.

**Comment by victorbalssa** [comment]
👍🏻  for the translation issue fixed,
Do you still experience issues with autocompletes ? can you describe a reproducible error so I can fix it in the next hot fix.

**Comment by dbilee** [comment]
Yes, some issues.
1. source and dest account only search in Liabilities accounts, Assets seems not included in add withdrawal and add transfer page, and didn't search the revenue accounts; in add deposit page, maybe this should keep the same as firefly III.
2. what about make the autocomplete list length configurable in [5,10]? 5 seems not enough sometimes.

Very expected for your update, thanks.

**Comment by dbilee** [comment]
@victorbalssa Thanks for your work, the problem 2 has been fixed 👍. But problem 1 still exists which makes it difficult to create transactions, can you help to take a look? Thanks 😊

**Comment by imlonghao** [comment]
How about do a url encode before sending the url to axios?

Rewrite this line

https://github.com/victorbalssa/abacus/blob/5ce522b901cde9bc27433d810d725b5a3b944bf7/src/models/accounts.ts#L168

to

```
 { url: `/api/v1/autocomplete/accounts?types=Asset%20account,${type},Loan,Debt,Mortgage&limit=${limit}&query=${encodeURIComponent(query)}` },
```

---

<del>PS, I deployed a Cloudflare worker to decode the space, works fine for me. XD</del>

```
export default {
  async fetch(request, env) {
    let url = new URL(request.url)
    url.host = "firefly.example.com"
    url.search = url.search.replaceAll('%2520', '%20')
    try {
      return await fetch(url.toString(), request);
    } catch (e) {
      return new Response(JSON.stringify({ error: e.message }), { status: 500 });
    }
  }
}
```

**Comment by victorbalssa** [comment]
@imlonghao with the last OTA update can you confirm that this is fixed ?

**Comment by imlonghao** [comment]
> @imlonghao with the last OTA update can you confirm that this is fixed ?

The OTA update works for me. Thanks.

**Comment by victorbalssa** [comment]
@dbilee I'll let you close this ticket if everything looks good on your end.

**Comment by dbilee** [comment]
> @dbilee I'll let you close this ticket if everything looks good on your end.

No, the autocompletion still not work in chinese. In create withdrawal and create transfer page,  the source and dest account only list labilities accounts,assets accounts.

**Comment by dbilee** [comment]
@victorbalssa Thanks for your work. If necessary I can test the fix for autocompletion.

**Comment by victorbalssa** [comment]
Thanks @dbilee, still a WIP, I'll send a msg here when I have a patch ready.

**Comment by victorbalssa** [comment]
@dbilee I tested with last version 0.6.2 with OTA update and everything is fine on the asset account auto complete with Chinese language.

![IMG_3915](https://github.com/victorbalssa/abacus/assets/12813321/28e4b1f2-ae1f-4f30-aa90-c089139ef885)
![IMG_3914](https://github.com/victorbalssa/abacus/assets/12813321/d83210db-bb3d-465e-8e3b-28d9516eb39c)

If it's still not working on your end could you please re-check your account configuration please?

**Comment by dbilee** [comment]
Cool! workd! Thanks very much!
